tracker/tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tracker_app.urls', namespace="tracker")),
    path('', include('users.urls', namespace="users")),
    path('expenses/', include('dashboard.urls', namespace="dashboard")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tracker/tracker_app/urls.py
from django.urls import path, include

from users.urls import app_name
from . import views

app_name = 'tracker'

urlpatterns = [
    path('', views.index, name='home'),
    path('expenses/', views.Expenses.as_view(), name='expense'),
    path('expenses/<int:pk>/', views.Expenses.as_view(), name='edit_expense'),
    path('expenses/create/', views.Expenses.as_view(), name='create_expense'),
    path('dict/', views.dictionary, name='dict'),
    path('category/', views.CategoryView.as_view(), name='category'),
    path('category/<int:pk>', views.CategoryView.as_view(), name='category_edit'),
    path('export/csv/', views.FileExportImport().templatecsv, name='export_csv'),
    path('upload/csv/', views.FileExportImport().readcsv, name='upload_csv'),
    path('export/excel/', views.FileExportImport().templatexcel, name='export_excel'),
]

tracker/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('registration/', views.RegisterUser.as_view(), name='registration')
]

tracker/users/models.py
from django.db import models

# Create your models here.

tracker/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserLoginForm(forms.Form):

    username = forms.CharField(label="User name", widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class UserCreateForm(UserCreationForm):
    username = forms.CharField(label="User name", widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label="Repeat password", widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'password1', 'password2']

tracker/users/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from .forms import UserLoginForm, UserCreateForm
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth import get_user_model
from django.contrib import messages

# Create your views here.


def login_user(request):

    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username = cd['username'], password = cd['password'])
            if user and user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('tracker:home'))
            # elif form.cleaned_data['username'] is None:
            if not get_user_model().objects.filter(username=cd['username']).exists():
                return HttpResponseRedirect(reverse('users:registration'))
    else:
        form = UserLoginForm()
    return render(request, 'users/login.html', {'form': form})


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('tracker:home'))


class RegisterUser(CreateView):
    form_class = UserCreateForm
    template_name = 'users/registration.html'
    extra_context = {'title': "Registration"}
    success_url = reverse_lazy('users:login')

tracker/users/templates/users/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'users/css/main_style.css' %}">
</head>


<body>

    <header class="d-flex flex-wrap align-items-center justify-content-between py-1 mb-4 border-bottom">
        <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-0 text-dark text-decoration-none">
            <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
            <span class="fs-4">Expense tracker</span>
        </a>
        <div class="container custom-container">
            <ul class="nav nav-pills justify-content-start">
                <li class="nav-item">
                    <a href="{% url 'tracker:home' %}" class="nav-link {% if request.path == '/' %}active{% endif %}" aria-current="page">Home</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'tracker:expense' %}" class="nav-link {% if request.path == '/expenses/' %}active{% endif %}">Expenses</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'tracker:dict' %}" class="nav-link {% if request.path == '/dict/' %}active{% endif %}">Dictionaries</a>
                </li>
                <li class="nav-item"><a href="#" class="nav-link">FAQs</a></li>
                <li class="nav-item"><a href="#" class="nav-link">About</a></li>
            </ul>
        </div>
        {% block export %}
        {% endblock %}
        <ul>
            {% if user.is_authenticated %}
                <div class="user-info">
                    <p>Welcome {{ user.username }}!</p>
                    <li class="btn btn-primary"><a href="{% url 'users:logout' %}" role="button" style="text-decoration: none; color: white;">Logout</a></li>
                </div>
            {% else %}
                <div class="user-info">
                    <p>Hello unknown!</p>
                    <li class="btn btn-primary"><a href="{% url 'users:login' %}" role="button" style="text-decoration: none; color: white;">Please login</a></li>
                </div>
            {% endif %}
        </ul>
    </header>

<!--    <aside>-->
<!--        {% block aside %}-->
<!--        {% endblock %}-->
<!--    </aside>-->

    <main>
        {% block body %}
        {% endblock %}
    </main>

</body>
</html>

tracker/users/templates/users/login.html
{% extends 'users/base.html' %}

{% block title %}
Authorization
{% endblock %}

{% block body%}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p><button type="submit">Enter</button></p>
</form>
{% endblock %}

tracker/users/templates/users/registration.html
{% extends 'users/base.html' %}

{% block title %}
Registration
{% endblock %}

{% block body%}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p><button type="submit">Register</button></p>
</form>
{% endblock %}