tracker/dashboard/urls.py
from django.urls import path

from users.urls import app_name
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('example_dashboard/', views.example_dashboard, name='example_dashboard')
]

tracker/tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tracker_app.urls', namespace="tracker")),
    path('', include('users.urls', namespace="users")),
    path('expenses/', include('dashboard.urls', namespace="dashboard")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tracker/tracker_app/urls.py
from django.urls import path, include

from users.urls import app_name
from . import views

app_name = 'tracker'

urlpatterns = [
    path('', views.index, name='home'),
    path('expenses/', views.Expenses.as_view(), name='expense'),
    path('expenses/<int:pk>/', views.Expenses.as_view(), name='edit_expense'),
    path('expenses/create/', views.Expenses.as_view(), name='create_expense'),
    path('dict/', views.dictionary, name='dict'),
    path('category/', views.CategoryView.as_view(), name='category'),
    path('category/<int:pk>', views.CategoryView.as_view(), name='category_edit'),
    path('export/csv/', views.FileExportImport().templatecsv, name='export_csv'),
    path('upload/csv/', views.FileExportImport().readcsv, name='upload_csv'),
    path('export/excel/', views.FileExportImport().templatexcel, name='export_excel'),
]

tracker/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('registration/', views.RegisterUser.as_view(), name='registration')
]

tracker/tracker_app/models.py
from tabnanny import verbose
from tkinter.constants import CASCADE
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from django.db import models

# Create your models here.

class Category(models.Model):

    name = models.CharField('category', max_length=250, unique=True)
    is_archive = models.BooleanField(default=False)


    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


def validate_positiv_decimal(value):
    if value < 0:
        raise ValidationError(f"{value} can`t be lower than 0")

class Expense(models.Model):

    date = models.DateField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2, validators=[validate_positiv_decimal])
    desc = models.TextField(blank=True, null=True)
    time_update = models.DateTimeField(auto_now=True)
    is_delete = models.BooleanField(default=False)

    def __str__(self):
        return f'category - {self.category}, amount - {self.amount} on {self.date}, updated - {self.time_update}'

    class Meta:
        verbose_name = 'Expense'
        verbose_name_plural = 'Expenses'

class UserExpenses(models.Model):

    expense = models.ForeignKey(Expense, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.expense} - {self.user}'

tracker/tracker_app/forms.py
from django import forms
from .models import Expense, Category



class ExpensesForm(forms.ModelForm):

    class Meta:
        model = Expense
        fields = ['date', 'category', 'amount', 'desc', 'is_delete']
        widgets = {
                    'date': forms.DateInput(attrs={'type': 'date'}),  # HTML5-виджет выбора даты
                }


class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = ['name', 'is_archive']


class UploadFile(forms.Form):
    csv_file = forms.FileField(label='Upalod file')

tracker/tracker_app/views.py
from distutils.core import extension_keywords
from http.client import responses
from imghdr import test_webp
from tokenize import Exponent

from django.contrib.admin import action
from django.db.models.expressions import result
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.template.context_processors import request
from django.views import View
from unicodedata import category

from .forms import ExpensesForm, CategoryForm, UploadFile
from .models import Expense, Category, UserExpenses
from django.views.generic import CreateView
from django.apps import apps

import csv
import pandas as pd
import datetime
import openpyxl
from io import StringIO

# Create your views here.

def index(request):
    return render(request, 'tracker_app/home.html')


def decorator(func):

    def wrapper(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return func(self, request,  *args, **kwargs)
        else:
            return redirect('users:login')
    return wrapper


class Expenses(View):

    # def get_filters(self, filter_category, filter_type, expenses_for_auth):
    #
    #     filters = {'id__in': expenses_for_auth}
    #
    #     if filter_category:
    #         try:
    #             filter_category = int(filter_category)
    #             filters['category'] = filter_category
    #         except ValueError:
    #             filter_category = None
    #
    #     if filter_type == 'active':
    #         filters['is_delete'] = False
    #     elif filter_type == 'deleted':
    #         filters['is_delete'] = True
    #
    #     return filters


    @decorator
    def get(self, request, pk=None):

        filter_type = request.GET.get('filter', 'active')
        filter_category = request.GET.get('filter_category', None)
        # filter_date = request.Get.get('filter_date', None)

        if filter_category:
            try:
                filter_category = int(filter_category)
            except ValueError:
                filter_category = None

        categories = Category.objects.all()
        list_for_auth = UserExpenses.objects.filter(user=request.user.id)
        expenses_for_auth = list_for_auth.values_list('expense', flat=True)
        today = datetime.date.today()

        if pk is None:
            if filter_category:
                exp_list = Expense.objects.filter(id__in=expenses_for_auth, category=filter_category).order_by("-date")
            else:
                exp_list = Expense.objects.filter(id__in=expenses_for_auth).order_by("-date")
            if filter_type == 'active':
                exp_list = exp_list.filter(is_delete=False)
            elif filter_type == 'deleted':
                exp_list = exp_list.filter(is_delete=True)
            # if filter_date:
            #     exp_list = Expense.objects.filter(id__in=expenses_for_auth, date=filter_date)
            # else:
            #     exp_list = Expense.objects.filter(id__in=expenses_for_auth)
            return render(request, 'tracker_app/expenses.html', {
                'exp_list': exp_list,
                'filter_type': filter_type,
                'filter_category': filter_category,
                'categories': categories,
                'today': today
            })

        else:
            exp = get_object_or_404(Expense, pk=pk)
            form = ExpensesForm(instance=exp)
            return render(request, 'tracker_app/expenses_edit.html', {'form': form, 'exp': exp, 'today': today})


    # def get_date(self, request):



    def post(self, request, pk=None):
        action = request.POST.get('action', 'create_expense')

        if action == 'edit_expense':
            return self.edit_expense(request, pk)
        elif action == 'delete_expense':
            return self.delete_expense(request, pk)
        elif action == 'archive_expense':
            return self.archive_expense(request, pk)
        else:
            return self.create_expense(request)

    def create_expense(self, request):
        form = ExpensesForm(request.POST)
        if form.is_valid():
            expense = form.save()
            UserExpenses.objects.create(user=request.user, expense=expense)
            return redirect('tracker:expense')
        else:
            return render(request, 'tracker_app/create_expense.html', {'form': form})


    def edit_expense(self, request, pk):

        expense = get_object_or_404(Expense, pk=pk)
        form = ExpensesForm(request.POST, instance=expense)

        if form.is_valid():
            form.save()
            return redirect('tracker:expense')
        else:
            return render(request, 'tracker_app/expenses_edit.html', {'expense': expense, 'form': form})

    def delete_expense(self, request, pk):

        expense = get_object_or_404(Expense, pk=pk)
        expense.delete()
        return redirect('tracker:expense')

    def archive_expense(self, request, pk):

        expense = get_object_or_404(Expense, pk=pk)
        expense.is_delete = True
        expense.save()
        return redirect('tracker:expense')



class CategoryView(View):

    @decorator
    def get(self, request, pk=None):
        """
        Если pk is None
        Вызвращаем весь список експенсов

        Если pk указан
        Вызвращаем только тот експенс, айди которого передали
        """
        if pk is None:
            # category_list = Category.objects.all()
            text_query = request.GET.get('search', '')
            category_list = self.get_filter_input(request, text_query)
            return render(request, 'tracker_app/category.html', {'category_list': category_list, 'text_query': text_query})

        else:
            categ = get_object_or_404(Category, pk=pk)
            form = CategoryForm( instance=categ)
            return render(request, 'tracker_app/category_edit.html', {'categ': categ, 'form': form})

    def get_filter_input(self, request, text_query):

        if text_query.strip():
            return Category.objects.filter(name__icontains=text_query.strip())
        return Category.objects.all()


    def post(self, request, pk=None):
        action = request.POST.get('action', 'create_category')

        if action == 'edit_category':
            return self.edit_category(request, pk)
        elif action == 'delete_category':
            return self.delete_category(request, pk)
        elif action == 'archive_category':
            return self.archive_category(request, pk)
        else:
            return self.create_category(request)


    def create_category(self, request):
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('tracker:category')
        else:
            return render(request, 'tracker_app/category.html', {'form': form})


    def edit_category(self, request, pk):
        category = get_object_or_404(Category, pk=pk)
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            return redirect('tracker:category')
        else:
            return render(request, 'tracker_app/category_edit.html', {'form': form, 'category': category})

    def delete_category(self, request, pk):
        category = get_object_or_404(Category, pk=pk)
        category.delete()
        return redirect('tracker:category')

    def archive_category(self, request, pk):
        category = get_object_or_404(Category, pk=pk)
        category.is_archive = True
        category.save()
        return redirect('tracker:category')




def dictionary(request):

    all_models = apps.get_models(include_auto_created=True, include_swapped=True)
    data = []

    for p in all_models:
        if 'tracker_app' in p._meta.app_label and 'user' not in p.__name__.lower():
            # data.append(f"tracker:{p.__name__.lower()}")
            data.append({
                'url': f"tracker:{p.__name__.lower()}",
                'name': p.__name__
            })

    return render(request, 'tracker_app/dict.html', {'data': data})


class FileExportImport(View):

    def templatecsv(self, request):

        fields = [
            ['date', 'category', 'amount', 'desc'],
        ]
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="expenses_template.csv"'

        writer = csv.writer(response)
        writer.writerows(fields)

        return response

    def readcsv(self, request):

        if request.method == 'POST':

            form = UploadFile(request.POST, request.FILES)
            file =[]
            if form.is_valid():
                raw_data = form.cleaned_data['csv_file']
                extension_file = raw_data.name.split('.')[-1].lower()
                if extension_file == 'xlsx':
                    raw_data = convert_excel_into_csv(raw_data)
                else:
                    raw_data = raw_data.read().decode('utf-8')

                decoded_file = raw_data.splitlines()
                reader = csv.DictReader(decoded_file)
                for fields in reader:
                    fields['date'] = convert_date(fields['date'])
                    fields['amount'] = fields['amount'].replace(',', '.')
                    category, category_created = Category.objects.get_or_create(name__iexact=fields['category'].strip())
                    expenses, expenses_created = Expense.objects.get_or_create(date=fields['date'],
                                                                      category=category,
                                                                      amount=fields['amount'],
                                                                      desc=fields['desc'])
                    expenses_user, expenses_user_created = UserExpenses.objects.get_or_create(user=request.user, expense=expenses)

tracker/tracker_app/templates/tracker_app/category.html
{% extends 'users/base.html' %}

{% block title %}
Categories
{% endblock %}

{% block body %}
<h2>Categories</h2>

<form method="GET" action="{% url 'tracker:category' %}">
    <input type="text" name="search" value="{{ text_query }}" placeholder="Search categories" minlength="3">
    <button type="submit">Search</button>
</form>

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Category name</th>
            <th>Edit</th>
        </tr>
    </thead>
    <tbody>
        {% for category in category_list %}
        <tr>
            <td>{{ category.name }}</td>
            <td><a href="{% url 'tracker:category_edit' pk=category.pk%}">Edit</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<form method="post">
    <h2>Create category</h2>
    {% csrf_token %}
    {{ form.as_table }}
    <p><button type="submit" name="action" value="create_category">Create category</button></p>
</form>
{% endblock %}

tracker/tracker_app/templates/tracker_app/category_edit.html
{% extends 'users/base.html' %}


{% block title %}
Edit category
{% endblock %}



{% block body%}
<form method="post">
    <h2>Edit category</h2>
    {% csrf_token %}
    {{ form.as_table }}
    <p><button type="submit" name="action" value="edit_category">Save changes</button></p>
</form>

<form method="post" action="{% url 'tracker:category_edit' pk=categ.pk %}">
    {% csrf_token %}
    <p><button type="submit" name="action"  value="delete_category">Irretrievably delete</button></p>
</form>

<form method="post" action="{% url 'tracker:category_edit' pk=categ.pk %}">
    {% csrf_token %}
    <p><button type="submit" name="action" value="archive_category">Delete with archive</button></p>
</form>
{% endblock %}

tracker/tracker_app/templates/tracker_app/create_expense.html
{% extends 'users/base.html' %}


{% block title %}
Create expenses
{% endblock %}



{% block body%}
<form method="post">
    <h2>Create expense</h2>
    {% csrf_token %}
    {{ form.as_p }}
    <p><button type="submit" name="action" value="create_expense">Create expense</button></p>
</form>
{% endblock %}

tracker/tracker_app/templates/tracker_app/dict.html
{% extends 'users/base.html' %}


{% block title %}
Navigation
{% endblock %}




{% block body%}

<aside>
<!--    <ul>-->
<!--        {% for p in exp %}-->
<!--            <li>{{ p }}</li>-->
<!--        {% endfor %}-->
<!--        {{ exp.model_name }}-->
<!--    </ul>-->
<!--    <a href="{% url 'tracker:expense' %}" style="text-decoration: none; color: black;">Expenses</a>-->
    <ul>
        {% for p in data %}
            <li><a href="{% url p.url %}">{{ p.name }}</a></li>
        {% endfor %}
    </ul>

</aside>

{% endblock %}

tracker/tracker_app/templates/tracker_app/expenses.html
{% extends 'users/base.html' %}


{% block title %}
Expenses
{% endblock %}

{% block export %}

    <body>
        <form action="{% url 'tracker:upload_csv' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ csv_form.as_p }}
            <button type="submit" class="btn btn-primary" style="margin-right: 3px;">Upload</button>
        </form>
    </body>

    <div class="dropdown">
        <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
            Download template
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <li><a class="dropdown-item" href="{% url 'tracker:export_csv' %}">CSV</a></li>
            <li><a class="dropdown-item" href="{% url 'tracker:export_excel' %}">EXCEL</a></li>
        </ul>
    </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>

{% endblock %}

{% block body%}
    <h2>List of expenses</h2>

    <a href="{% url 'dashboard:example_dashboard' %}">Dashboard</a>

    <form method="get">
       <label for="filter">Фильтр расходов:</label>
            <select  class="form-select custom-width" aria-label="Default select example" name="filter" id="filter" onchange="this.form.submit()">
                <option value="all" {% if filter_type == 'all' %}selected{% endif %}>Показать все расходы</option>
                <option value="active" {% if filter_type == 'active' %}selected{% endif %}>Показать только активные</option>
                <option value="deleted" {% if filter_type == 'deleted' %}selected{% endif %}>Показать только удалённые</option>
            </select>

       <label for="filter_category">Категория:</label>
            <select class="form-select custom-width" name="filter_category" id="filter_category" onchange="this.form.submit()">
                <option value="">Select Category</option>
                {% for category in categories %}
                    <option value="{{ category.id }}" {% if category.id == filter_category %}selected{% endif %}>
                        {{ category.name }}
                    </option>
                {% endfor %}
            </select>

       <label for="filter_category">Дата:</label>
            <select class="form-select custom-width" name="filter_date" id="filter_date" onchange="this.form.submit()">
                <option value="">Select Date</option>
                {% for category in categories %}
                    <option value="{{ category.id }}" {% if category.id == filter_category %}selected{% endif %}>
                        {{ category.name }}
                    </option>
                {% endfor %}
            </select>
    </form>


    <table class="table table-striped table-hover">
        <thead>
            <tr >
                <th>Date</th>
                <th>Category</th>
                <th>Amount</th>
                <th>Description</th>
                <th>Edit</th>
            </tr>
        </thead>
        <tbody>
            {% for expense in exp_list %}
            <tr>
                <td>{{ expense.date }}</td>
                <td>{{ expense.category.name }}</td>
                <td>{{ expense.amount }}</td>
                <td>{{ expense.desc }}</td>
                <td><a href="{% url 'tracker:edit_expense' pk=expense.pk %}">Edit</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
<form action="{% url 'tracker:create_expense' %}" method="post">
    <h2>Create expense</h2>
    {% csrf_token %}
    {{ form.as_table }}
    <p><button type="submit" name="action" value="create_expense">Create expense</button></p>
</form>
{% endblock %}

tracker/tracker_app/templates/tracker_app/expenses_edit.html
{% extends 'users/base.html' %}


{% block title %}
Edit expenses
{% endblock %}



{% block body%}
<form method="post">
    <h2>Edit expense</h2>
    {% csrf_token %}
    {{ form.as_table }}
    <p><button type="submit" name="action" value="edit_expense">Save changes</button></p>
</form>

<form method="post" action="{% url 'tracker:edit_expense' pk=exp.pk %}">
    {% csrf_token %}
    <p><button type="submit" name="action" value="delete_expense">Irretrievably delete</button></p>
</form>

<form method="post" action="{% url 'tracker:edit_expense' pk=exp.pk %}">
    {% csrf_token %}
    <p><button type="submit" name="action" value="archive_expense">Archive</button></p>
</form>
{% endblock %}

tracker/tracker_app/templates/tracker_app/home.html
{% extends 'users/base.html' %}

{% block title %}
Hello this is the home page of the expenses tracker app
{% endblock %}